-- Resort Guest Operations Copilot
-- Portfolio demo schema for Supabase PostgreSQL + pgvector.

create extension if not exists vector;

-- ---------------------------------------------------------------------------
-- RAG knowledge base
-- ---------------------------------------------------------------------------

create table if not exists public.resort_documents (
  id bigint generated by default as identity primary key,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(3072) not null
);

create index if not exists resort_documents_metadata_gin_idx
  on public.resort_documents using gin (metadata);

-- The demo intentionally uses exact vector search. pgvector's standard HNSW
-- index does not support 3072-dimensional vectors.
create or replace function public.match_resort_documents(
  query_embedding vector(3072),
  match_count integer default 5,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity double precision
)
language sql
stable
set search_path = public
as $$
  select
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) as similarity
  from public.resort_documents as d
  where d.metadata @> filter
  order by d.embedding <=> query_embedding
  limit greatest(match_count, 0);
$$;

-- ---------------------------------------------------------------------------
-- Operational audit trail
-- ---------------------------------------------------------------------------

create table if not exists public.resort_operations_requests (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  message_id text,
  chat_id text not null,
  sender_open_id text,
  employee_message text not null,
  category text not null default 'Other',
  priority text not null default 'Normal',
  summary text,
  suggested_reply text,
  route text not null default 'routine'
    check (route in ('routine', 'manager_approval', 'human_escalation')),
  requires_approval boolean not null default false,
  needs_human_escalation boolean not null default false,
  status text not null default 'received'
    check (status in ('received', 'acknowledged', 'pending_approval', 'escalated')),
  rag_grounded boolean not null default false,
  sop_source text,
  sop_version text,
  retrieval_count integer not null default 0 check (retrieval_count >= 0),
  retrieval_top_score double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists resort_operations_requests_created_at_idx
  on public.resort_operations_requests (created_at desc);

create index if not exists resort_operations_requests_route_status_idx
  on public.resort_operations_requests (route, status);

-- ---------------------------------------------------------------------------
-- Service-booking request ledger
-- ---------------------------------------------------------------------------

create table if not exists public.resort_service_bookings (
  id bigint generated by default as identity primary key,
  booking_reference text not null unique,
  source_event_id text not null unique,
  target_booking_reference text,
  request_action text not null
    check (request_action in ('create', 'modify', 'cancel')),
  service_type text not null
    check (service_type in (
      'spa',
      'restaurant',
      'airport_transfer',
      'resort_activity',
      'facility_timeslot'
    )),
  room_number text,
  requested_date date,
  requested_time time,
  guest_count integer check (guest_count is null or guest_count > 0),
  flight_number text,
  terminal text,
  pickup_location text,
  luggage_count integer check (luggage_count is null or luggage_count >= 0),
  special_requests text,
  missing_fields jsonb not null default '[]'::jsonb,
  request_details jsonb not null default '{}'::jsonb,
  approval_required boolean not null default false,
  human_review_required boolean not null default true,
  ready_for_availability_check boolean not null default false,
  workflow_status text not null
    check (workflow_status in (
      'pending_information',
      'pending_approval',
      'pending_availability',
      'modification_requested',
      'cancellation_requested'
    )),
  source_message text not null,
  summary text,
  employee_reply text,
  rag_grounded boolean not null default false,
  sop_source text,
  sop_version text,
  retrieval_count integer not null default 0 check (retrieval_count >= 0),
  retrieval_top_score double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists resort_service_bookings_target_reference_idx
  on public.resort_service_bookings (target_booking_reference);

create index if not exists resort_service_bookings_status_idx
  on public.resort_service_bookings (workflow_status, created_at desc);

-- ---------------------------------------------------------------------------
-- Timestamp maintenance
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_resort_operations_requests_updated_at
  on public.resort_operations_requests;

create trigger set_resort_operations_requests_updated_at
before update on public.resort_operations_requests
for each row execute function public.set_updated_at();

drop trigger if exists set_resort_service_bookings_updated_at
  on public.resort_service_bookings;

create trigger set_resort_service_bookings_updated_at
before update on public.resort_service_bookings
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Server-side access boundary
-- ---------------------------------------------------------------------------

alter table public.resort_documents enable row level security;
alter table public.resort_operations_requests enable row level security;
alter table public.resort_service_bookings enable row level security;

revoke all on table public.resort_documents from anon, authenticated;
revoke all on table public.resort_operations_requests from anon, authenticated;
revoke all on table public.resort_service_bookings from anon, authenticated;

grant usage on schema public to service_role;
grant all on table public.resort_documents to service_role;
grant all on table public.resort_operations_requests to service_role;
grant all on table public.resort_service_bookings to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.match_resort_documents(vector, integer, jsonb)
  to service_role;

